### ISSUE TITLE
Configurar las entidedades de Spring

### ISSUE THREAD

**Issue by jnunez2301** [corePracticas/proyectoPracticasCore#1]
Necesitamos añadir la clase Clientes en el apartado de User para que tengamos un funcionamiento correcto con las entidades

**Comment by JoaoCzz** [comment]
Añadi en modelo la clase "client" haciendo referencia a clientes con los parametros proporcionados en el pdf.
![image](https://github.com/corePracticas/proyectoPracticasCore/assets/147420438/39a9f711-1d47-466b-a153-478dffaccabf)
